/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginRegister;

import java.awt.Color;
import java.nio.charset.Charset;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import java.util.*;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Ridho Gymnastiar Al Rasyid 1402020069 | Aldhaf Fadlilah 1402020112
 */
public class LoginRegister extends javax.swing.JFrame {

    /**
     * Creates new form FormRegister
     */
    // Create Borders
    Border default_top_border = BorderFactory.createMatteBorder(2, 0, 0, 0, new Color(204, 204, 204));
    Border red_top_border = BorderFactory.createMatteBorder(2, 0, 0, 0, Color.red);
    Border textField_border = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red);

    private boolean flagA, flagB, flagC;
    private KoneksiDB db = new KoneksiDB();
    protected String username, pw;

    // Constructor
    public LoginRegister() {
        initComponents();
        jPanel_Login.setVisible(true);
        jPanel_Register.setVisible(false);
        jPanel_Main.setVisible(true);
        new UpdatePassword().setVisible(false);
        new Welcome().setVisible(false);
        // center form
        this.setLocationRelativeTo(null);

        // set borders
        jLabel_Login.setBorder(default_top_border);
        jLabel_Register.setBorder(default_top_border);
        jTextField_Login_username.setBorder(textField_border);
        jPasswordField_Login_pass.setBorder(textField_border);
        jTextField_Register_username.setBorder(textField_border);
        jTextField_Register_email.setBorder(textField_border);
        jPasswordField_Register_pass.setBorder(textField_border);

        // show icons
        jLabel_Close.setIcon(new ImageIcon(getClass().getResource("images/x-mark.png")));
        jLabel_Login_username.setIcon(new ImageIcon(getClass().getResource("images/contacts.png")));
        jLabel_Login_Password.setIcon(new ImageIcon(getClass().getResource("images/lock.png")));
        jLabel_Register_username.setIcon(new ImageIcon(getClass().getResource("images/contacts.png")));
        jLabel_Register_email.setIcon(new ImageIcon(getClass().getResource("images/email.png")));
        jLabel_Register_pass.setIcon(new ImageIcon(getClass().getResource("images/lock.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Container = new javax.swing.JPanel();
        jPanel_Main = new javax.swing.JPanel();
        jLabel_Register = new javax.swing.JLabel();
        jLabel_Login = new javax.swing.JLabel();
        jPanel_Login = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jTextField_Login_username = new javax.swing.JTextField();
        jPasswordField_Login_pass = new javax.swing.JPasswordField();
        jButton_Login = new javax.swing.JButton();
        jLabel_Login_username = new javax.swing.JLabel();
        jLabel_Login_Password = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_Register = new javax.swing.JPanel();
        jTextField_Register_username = new javax.swing.JTextField();
        jLabel_Register_username = new javax.swing.JLabel();
        jTextField_Register_email = new javax.swing.JTextField();
        jLabel_Register_email = new javax.swing.JLabel();
        jPasswordField_Register_pass = new javax.swing.JPasswordField();
        jLabel_Register_pass = new javax.swing.JLabel();
        jButton_Register1 = new javax.swing.JButton();
        jButton_GeneratePass = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel_error1 = new javax.swing.JLabel();
        jLabel_error2 = new javax.swing.JLabel();
        jLabel_error3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_Main.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Register.setBackground(new java.awt.Color(42, 187, 155));
        jLabel_Register.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel_Register.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Register.setText("Register");
        jLabel_Register.setToolTipText("");
        jLabel_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Register.setOpaque(true);
        jLabel_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RegisterMouseClicked(evt);
            }
        });

        jLabel_Login.setBackground(new java.awt.Color(42, 187, 155));
        jLabel_Login.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel_Login.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Login.setText("Login");
        jLabel_Login.setToolTipText("");
        jLabel_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Login.setOpaque(true);
        jLabel_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LoginMouseClicked(evt);
            }
        });

        jPanel_Login.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Login.setPreferredSize(new java.awt.Dimension(376, 363));
        jPanel_Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox2.setText("Show Password");
        jCheckBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel_Login.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, 20));

        jTextField_Login_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Login_username.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Login_username.setText("username");
        jTextField_Login_username.setOpaque(false);
        jTextField_Login_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_Login_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_Login_usernameFocusLost(evt);
            }
        });
        jPanel_Login.add(jTextField_Login_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 272, -1));

        jPasswordField_Login_pass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_Login_pass.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_Login_pass.setText("password");
        jPasswordField_Login_pass.setOpaque(false);
        jPasswordField_Login_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_Login_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_Login_passFocusLost(evt);
            }
        });
        jPanel_Login.add(jPasswordField_Login_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 272, -1));

        jButton_Login.setBackground(new java.awt.Color(255, 153, 0));
        jButton_Login.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButton_Login.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Login.setText("Login");
        jButton_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginActionPerformed(evt);
            }
        });
        jPanel_Login.add(jButton_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 305, 50));
        jPanel_Login.add(jLabel_Login_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 28, 28));
        jPanel_Login.add(jLabel_Login_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 28, 28));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\Untitled design (2).png")); // NOI18N
        jPanel_Login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 363));

        jPanel_Register.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Register.setMinimumSize(new java.awt.Dimension(365, 210));
        jPanel_Register.setPreferredSize(new java.awt.Dimension(376, 363));
        jPanel_Register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField_Register_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Register_username.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Register_username.setText("username");
        jTextField_Register_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_Register_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_Register_usernameFocusLost(evt);
            }
        });
        jTextField_Register_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Register_usernameKeyReleased(evt);
            }
        });
        jPanel_Register.add(jTextField_Register_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 272, -1));
        jPanel_Register.add(jLabel_Register_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 30, 28));

        jTextField_Register_email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Register_email.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Register_email.setText("email");
        jTextField_Register_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_Register_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_Register_emailFocusLost(evt);
            }
        });
        jTextField_Register_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Register_emailKeyReleased(evt);
            }
        });
        jPanel_Register.add(jTextField_Register_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 272, -1));

        jLabel_Register_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel_Register_emailKeyReleased(evt);
            }
        });
        jPanel_Register.add(jLabel_Register_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 30, 28));

        jPasswordField_Register_pass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_Register_pass.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_Register_pass.setText("password");
        jPasswordField_Register_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_Register_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_Register_passFocusLost(evt);
            }
        });
        jPasswordField_Register_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField_Register_passKeyReleased(evt);
            }
        });
        jPanel_Register.add(jPasswordField_Register_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 272, -1));
        jPanel_Register.add(jLabel_Register_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 30, 28));

        jButton_Register1.setBackground(new java.awt.Color(25, 181, 254));
        jButton_Register1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButton_Register1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Register1.setText("Register");
        jButton_Register1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Register1ActionPerformed(evt);
            }
        });
        jPanel_Register.add(jButton_Register1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 305, 50));

        jButton_GeneratePass.setBackground(new java.awt.Color(51, 255, 255));
        jButton_GeneratePass.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton_GeneratePass.setText("Generate Password");
        jButton_GeneratePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_GeneratePass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_GeneratePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GeneratePassActionPerformed(evt);
            }
        });
        jPanel_Register.add(jButton_GeneratePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 140, 30));

        jCheckBox1.setText("Show Password");
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel_Register.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 120, 30));

        jLabel_error1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel_error1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_error1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_Register.add(jLabel_error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 270, 20));

        jLabel_error2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel_error2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_error2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_Register.add(jLabel_error2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 270, 20));

        jLabel_error3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jLabel_error3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_error3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel_Register.add(jLabel_error3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 270, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\Untitled design (3).png")); // NOI18N
        jPanel_Register.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 363));

        javax.swing.GroupLayout jPanel_MainLayout = new javax.swing.GroupLayout(jPanel_Main);
        jPanel_Main.setLayout(jPanel_MainLayout);
        jPanel_MainLayout.setHorizontalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_MainLayout.createSequentialGroup()
                .addComponent(jLabel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_MainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel_MainLayout.setVerticalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MainLayout.createSequentialGroup()
                .addGroup(jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_MainLayout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addComponent(jPanel_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ContainerLayout = new javax.swing.GroupLayout(jPanel_Container);
        jPanel_Container.setLayout(jPanel_ContainerLayout);
        jPanel_ContainerLayout.setHorizontalGroup(
            jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_ContainerLayout.setVerticalGroup(
            jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            jPasswordField_Register_pass.setEchoChar((char) 0);
        } else {
            jPasswordField_Register_pass.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    // Regex generate PASSWORD
    private void jButton_GeneratePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GeneratePassActionPerformed
        // TODO add your handling code here:
        jPasswordField_Register_pass.setText(generateRegex());
        jPasswordField_Register_pass.setForeground(Color.black);
        jLabel_error3.setText("");
        flagC = true;
    }//GEN-LAST:event_jButton_GeneratePassActionPerformed

    private void jButton_Register1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Register1ActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == jButton_Register1) {
            if (flagA && flagB && flagC) {
                db.koneksiDatabase();
                try {
                    Connection dbconnect = db.getKoneksi();
                    String query = " insert into user (username, email, password)"
                            + " values(?, ?, ?)";
                    PreparedStatement myStatement = dbconnect.prepareStatement(query);
                    myStatement.setString(1, jTextField_Register_username.getText());
                    myStatement.setString(2, jTextField_Register_email.getText());
                    myStatement.setString(3, jPasswordField_Register_pass.getText());
                    myStatement.execute();
                    JOptionPane.showMessageDialog(null, "Register Berhasil");
                    jTextField_Register_username.setText("");
                    jTextField_Register_email.setText("");
                    jPasswordField_Register_pass.setText("");
                    jPanel_Login.setVisible(true);
                    jPanel_Register.setVisible(false);
                    // design jLabel login click
                    jLabel_Login.setBorder(red_top_border);
                    jLabel_Login.setBackground(Color.white);
                    jLabel_Login.setForeground(Color.black);

                    // design jLabel register click
                    jLabel_Register.setBorder(default_top_border);
                    jLabel_Register.setBackground(new Color(42, 187, 155));
                    jLabel_Register.setForeground(Color.white);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "ERROR");
                }
            } else {
                JOptionPane.showMessageDialog(null, "ERROR TIDAK VALID REGISTRASI", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButton_Register1ActionPerformed

    // Regex PASSWORD
    private void jPasswordField_Register_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_Register_passKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^([a-zA-Z0-9])+$";
        if (jPasswordField_Register_pass.getText().matches(PATTERN)) {
            jLabel_error3.setText("");
            flagC = true;
            if (jPasswordField_Register_pass.getText().length() < 8) {
                jLabel_error3.setText("ERROR PANJANG PASSWORD < 8");
                flagC = false;
            }
            if (jPasswordField_Register_pass.getText().length() > 12) {
                jLabel_error3.setText("ERROR PANJANG PASSWORD > 12");
                flagC = false;
            }
        } else {
            jLabel_error3.setText("ERROR PASSWORD TIDAK VALID");
            flagC = false;
        }
        if (jPasswordField_Register_pass.getText().equals("")) {
            jLabel_error3.setText("");
            flagC = false;
        }
    }//GEN-LAST:event_jPasswordField_Register_passKeyReleased

    private void jPasswordField_Register_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_Register_passFocusLost
        // TODO add your handling code here:
        String passValue = String.valueOf(jPasswordField_Register_pass.getPassword()).trim().toLowerCase();

        if (passValue.equals("password") || passValue.equals("")) {
            jPasswordField_Register_pass.setText("password");
            jPasswordField_Register_pass.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jPasswordField_Register_passFocusLost

    private void jPasswordField_Register_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_Register_passFocusGained
        // TODO add your handling code here:
        String passValue = String.valueOf(jPasswordField_Register_pass.getPassword()).trim().toLowerCase();

        if (passValue.equals("password")) {
            jPasswordField_Register_pass.setText("");
            jPasswordField_Register_pass.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField_Register_passFocusGained

    private void jLabel_Register_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel_Register_emailKeyReleased
        // TODO add your handling code here:z
    }//GEN-LAST:event_jLabel_Register_emailKeyReleased

    // Regex EMAIL
    private void jTextField_Register_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Register_emailKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9._%-]+@([a-zA-Z]{2,5})+(\\.[a-z]{2,5})+$";
        if (jTextField_Register_email.getText().matches(PATTERN)) {
            jLabel_error2.setText("");
            flagB = true;
            db.koneksiDatabase();
            try {
                String sql = "SELECT * FROM user WHERE email = '" + jTextField_Register_email.getText() + "'";
                Statement st = db.getKoneksi().createStatement();
                ResultSet rsLogin = st.executeQuery(sql);

                rsLogin.next();
                if (rsLogin.getRow() == 1) {
                    Random r = new Random();
                    String x = jTextField_Register_email.getText();
                    String tmp = null;
                    String[] random = new String[3];
                    int tmpz = 0;
                    for (int i = 0; i < x.length(); i++) {
                        if (x.charAt(i) == '@') {
                            tmp = x.substring(0, i);
                            tmpz = i;
                        }
                    }
                    int i = 0;
                    while (i < random.length) {
                        random[i] = tmp + r.nextInt(999) + x.substring(tmpz);
                        i++;
                    }
                    JOptionPane.showMessageDialog(null, "Email yang disarankan: \n"
                            + "1. " + random[0]
                            + "\n2. " + random[1]
                            + "\n3. " + random[2],
                            "EMAIL SUDAH TERDAFTAR", JOptionPane.INFORMATION_MESSAGE);
                    flagB = false;
                } else {
                    jLabel_error2.setText("");
                    flagB = true;
                }
            } catch (Exception e) {

            }
        } else {
            jLabel_error2.setText("ERROR EMAIL TIDAK VALID");
            flagB = false;
        }
        if (jTextField_Register_email.getText().equals("")) {
            jLabel_error2.setText("");
            flagB = false;
        }
    }//GEN-LAST:event_jTextField_Register_emailKeyReleased

    private void jTextField_Register_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Register_emailFocusLost
        // TODO add your handling code here:
        String email = jTextField_Register_email.getText().trim().toLowerCase();

        if (email.equals("email") || email.equals("")) {
            jTextField_Register_email.setText("email");
            jTextField_Register_email.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField_Register_emailFocusLost

    private void jTextField_Register_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Register_emailFocusGained
        // TODO add your handling code here:
        String email = jTextField_Register_email.getText().trim().toLowerCase();

        if (email.equals("email")) {
            jTextField_Register_email.setText("");
            jTextField_Register_email.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_Register_emailFocusGained

    // Regex Username
    private void jTextField_Register_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Register_usernameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^([a-zA-Z0-9.])+$";
        if (jTextField_Register_username.getText().matches(PATTERN)) {
            jLabel_error1.setText("");
            flagA = true;
            db.koneksiDatabase();
            try {
                String sql = "SELECT * FROM user WHERE username = '" + jTextField_Register_username.getText() + "'";
                Statement st = db.getKoneksi().createStatement();
                ResultSet rsLogin = st.executeQuery(sql);

                rsLogin.next();
                if (rsLogin.getRow() == 1) {
                    Random r = new Random();
                    JOptionPane.showMessageDialog(null, "Username yang disarankan: \n"
                            + "1. " + jTextField_Register_username.getText() + r.nextInt(999)
                            + "\n2. " + jTextField_Register_username.getText() + r.nextInt(999)
                            + "\n3. " + jTextField_Register_username.getText() + r.nextInt(999),
                            "USERNAME SUDAH TERDAFTAR", JOptionPane.INFORMATION_MESSAGE);
                    flagA = false;
                } else {
                    jLabel_error1.setText("");
                    flagA = true;
                }
            } catch (Exception e) {

            }
            if (jTextField_Register_username.getText().length() < 8) {
                jLabel_error1.setText("ERROR PANJANG USERNAME < 8");
                flagA = false;
            }
            if (jTextField_Register_username.getText().length() > 12) {
                jLabel_error1.setText("ERROR PANJANG USERNAME > 12");
                flagA = false;
            }
        } else {
            jLabel_error1.setText("ERROR USERNAME TIDAK VALID");
            flagA = false;
        }
        if (jTextField_Register_username.getText().equals("")) {
            jLabel_error1.setText("");
            flagA = false;
        }
    }//GEN-LAST:event_jTextField_Register_usernameKeyReleased

    private void jTextField_Register_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Register_usernameFocusLost
        // TODO add your handling code here:
        // textfield empty -> set text 'username'
        String usernameValue = jTextField_Register_username.getText().trim().toLowerCase();

        if (usernameValue.equals("username") || usernameValue.equals("")) {
            jTextField_Register_username.setText("username");
            jTextField_Register_username.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField_Register_usernameFocusLost

    private void jTextField_Register_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Register_usernameFocusGained
        // TODO add your handling code here:
        String usernameValue = jTextField_Register_username.getText().trim().toLowerCase();

        if (usernameValue.equals("username")) {
            jTextField_Register_username.setText("");
            jTextField_Register_username.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_Register_usernameFocusGained

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == jButton_Login) {
            db.koneksiDatabase();
            try {
                String sql = "SELECT * FROM user WHERE username = '"
                        + jTextField_Login_username.getText()
                        + "' AND password = '" + jPasswordField_Login_pass.getText() + "'";
                Statement st = db.getKoneksi().createStatement();
                ResultSet rsLogin = st.executeQuery(sql);
                String username = jTextField_Login_username.getText();
                String pass = jPasswordField_Login_pass.getText();

                rsLogin.next();
                if (rsLogin.getRow() == 1) {
                    username = rsLogin.getString("username");
                    pw = rsLogin.getString("password");
                    Welcome welcome = new Welcome();
                    welcome.username = username;
                    welcome.pw = pw;
                    welcome.setLabel(username);
                    welcome.setVisible(true);
                    this.setVisible(false);
                    jTextField_Login_username.setText(null);
                    jPasswordField_Login_pass.setText(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Maaf, Username / Password salah!");
                    jTextField_Login_username.setText(null);
                    jPasswordField_Login_pass.setText(null);
                }
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_jButton_LoginActionPerformed

    private void jPasswordField_Login_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_Login_passFocusLost
        // password empty -> set pass 'password'
        String passValue = String.valueOf(jPasswordField_Login_pass.getPassword()).trim().toLowerCase();

        if (passValue.equals("password") || passValue.equals("")) {
            jPasswordField_Login_pass.setText("password");
            jPasswordField_Login_pass.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jPasswordField_Login_passFocusLost

    private void jPasswordField_Login_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_Login_passFocusGained
        // if the jpassword text = password -> clear the textfield
        String passValue = String.valueOf(jPasswordField_Login_pass.getPassword()).trim().toLowerCase();

        if (passValue.equals("password")) {
            jPasswordField_Login_pass.setText("");
            jPasswordField_Login_pass.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField_Login_passFocusGained

    private void jTextField_Login_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Login_usernameFocusLost
        // textfield empty -> set text 'username'
        String usernameValue = jTextField_Login_username.getText().trim().toLowerCase();

        if (usernameValue.equals("username") || usernameValue.equals("")) {
            jTextField_Login_username.setText("username");
            jTextField_Login_username.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField_Login_usernameFocusLost

    private void jTextField_Login_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Login_usernameFocusGained
        // if the textField = username then clear the username
        String usernameValue = jTextField_Login_username.getText().trim().toLowerCase();

        if (usernameValue.equals("username")) {
            jTextField_Login_username.setText("");
            jTextField_Login_username.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_Login_usernameFocusGained

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox2.isSelected()) {
            jPasswordField_Login_pass.setEchoChar((char) 0);
        } else {
            jPasswordField_Login_pass.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jLabel_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LoginMouseClicked
        // display login panel
        jPanel_Login.setVisible(true);
        jPanel_Register.setVisible(false);

        // design jLabel login click
        jLabel_Login.setBorder(red_top_border);
        jLabel_Login.setBackground(Color.white);
        jLabel_Login.setForeground(Color.black);

        // design jLabel register click
        jLabel_Register.setBorder(default_top_border);
        jLabel_Register.setBackground(new Color(42, 187, 155));
        jLabel_Register.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_LoginMouseClicked

    private void jLabel_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegisterMouseClicked
        // display register panel
        jPanel_Register.setVisible(true);
        jPanel_Login.setVisible(false);

        // design jLabel register click
        jLabel_Register.setBorder(red_top_border);
        jLabel_Register.setBackground(Color.white);
        jLabel_Register.setForeground(Color.black);

        // design jLabel login click
        jLabel_Login.setBorder(default_top_border);
        jLabel_Login.setBackground(new Color(42, 187, 155));
        jLabel_Login.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_RegisterMouseClicked

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        // close this
        System.exit(0);
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    // generate Regex PASSWORD
    private static String generateRegex() {
        String pattern = "[^A-Za-z0-9]+";
        // 256 Character
        byte[] array = new byte[256];
        new Random().nextBytes(array);
        String randomString = new String(array, Charset.forName("UTF-8"));
        // StringBuilder untuk mengisi regex.charAt di dalam for
        StringBuilder result = new StringBuilder();
        // assignment pattern
        String regex = randomString.replaceAll(pattern, "");
        // generate password dengan panjang random 8-12 dengan ketentuan pattern regex
        int n = 12;
        for (int i = 0; i <= new Random().nextInt(8, 13); i++) {
            if (Character.isLetter(regex.charAt(i)) && (n > 0) || Character.isDigit(regex.charAt(i)) && (n > 0)) {
                result.append(regex.charAt(i));
                n--;
            }
        }
        // mengembalikan result
        return result.toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginRegister().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_GeneratePass;
    private javax.swing.JButton jButton_Login;
    private javax.swing.JButton jButton_Register1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_Login;
    private javax.swing.JLabel jLabel_Login_Password;
    private javax.swing.JLabel jLabel_Login_username;
    private javax.swing.JLabel jLabel_Register;
    private javax.swing.JLabel jLabel_Register_email;
    private javax.swing.JLabel jLabel_Register_pass;
    private javax.swing.JLabel jLabel_Register_username;
    private javax.swing.JLabel jLabel_error1;
    private javax.swing.JLabel jLabel_error2;
    private javax.swing.JLabel jLabel_error3;
    private javax.swing.JPanel jPanel_Container;
    private javax.swing.JPanel jPanel_Login;
    private javax.swing.JPanel jPanel_Main;
    private javax.swing.JPanel jPanel_Register;
    private javax.swing.JPasswordField jPasswordField_Login_pass;
    private javax.swing.JPasswordField jPasswordField_Register_pass;
    private javax.swing.JTextField jTextField_Login_username;
    private javax.swing.JTextField jTextField_Register_email;
    private javax.swing.JTextField jTextField_Register_username;
    // End of variables declaration//GEN-END:variables
}
